### ISSUE TITLE
Cephpool - Invalid check parameter: The type must be a dictionary, but it is a list!

### ISSUE THREAD

**Issue by marmot21** [HeinleinSupport/check_mk#12]
I am running check_mk 1.2.8p5 and I am gettting the following error with the cephpool check:
Invalid check parameter: The type must be a dictionary, but it is a list! The parameter is: [] The variable name is: checkgroup_parameters:filesystem

**Comment by gurubert** [comment]
The API of the filesystem check has been changed in 1.2.8.
The cephpool check has to be adapted.

**Comment by dnauck** [comment]
@gurubert  Do you plan to update the package?
