### ISSUE TITLE
Error after installing 

### ISSUE THREAD

**Issue by n3roGit** [HeinleinSupport/check_mk#13]
I use OMD 1.2.8p4 and get the following error after install the plug in and clicking wato.

`Traceback (most recent call last):
File "/omd/sites/COMPANY/share/check_mk/web/htdocs/wato.py", line 234, in page_handler
modefunc("buttons")
File "/omd/sites/COMPANY/share/check_mk/web/htdocs/wato.py", line 12176, in mode_edit_ruleset
groupname = g_rulegroups[group][0]
KeyError: 'agents'`

**Comment by gurubert** [comment]
Which check exactly did you install?

**Comment by n3roGit** [comment]
this one: https://github.com/HeinleinSupport/check_mk/tree/master/netifaces

**Comment by gurubert** [comment]
With "OMD 1.2.8p4" do you mean OMD 1.30, Check_MK Raw Edition 1.2.8p4 or Check_MK Enterprise Edition 1.2.8p4?

I think the bakery plugins only work for the Enterprise Edition. Please remove the file web/plugins/wato/agent_bakery_netifaces.py if you do not have an Enterprise Edition and try again.

**Comment by n3roGit** [comment]
Yes i use the free version. i will try :)
