### ISSUE TITLE
entropy_avail incompatible with Check_MK 1.2.8?

### ISSUE THREAD

**Issue by troelsarvin** [HeinleinSupport/check_mk#14]
I installed the latest relase of the entropy_avail mkp package in Check_MK 1.2.8p11 installation. After this, I started getting errors in the WATO web interface:
  Check parameter definition for entropy_avail has type Dictionary, but match_type None
Maybe entropy_avail needs to be adjusted for a newer Check_MK generation?

**Comment by gurubert** [comment]
The latest release has match = "dict" in the check parameters definition.

**Comment by troelsarvin** [comment]
I don't quite understand. I don't see any recent releases of the package.
