### ISSUE TITLE
MKP does not work with 1.2.8p13

### ISSUE THREAD

**Issue by UU0113** [HeinleinSupport/check_mk#17]
- Upload the MKP via WATO "Extension Packages".
- try to activate the change ends with:

"Check parameter definition for entropy_avail has type Dictionary, but match_type None"

**Comment by gurubert** [comment]
Hi UU0113,

which MKP did you try do install?

**Comment by gurubert** [comment]
match_type = "dict" set fixed in b05d9a689bad5e53826202b4c8c2eb1d3494d54d
MKP version 2.1
