### ISSUE TITLE
redis check will unknown when database is emptied out.

### ISSUE THREAD

**Issue by theundefined** [HeinleinSupport/check_mk#21]
Scenario:
redis with non empty db, it's inventarized as:
OK - db0: None (warn/crit at None/None)

when db is emptied(all keys were removed) - that check will disappear:
UNKNOWN - check failed - please submit a crash report!

by the way - there is lack of performance data for that checks.

check_mk 1.2.6p2, plugin to redis from current master, redis 2.8.17

**Comment by gurubert** [comment]
Performance data is written when you enable it in the check parameters.

And for the UNKNOWN for the empty database: please check the latest code I just integrated from the upstream author. You may need to setup new check parameter rules.
