### ISSUE TITLE
cephpools: invalid check parameter

### ISSUE THREAD

**Issue by fipsofant** [HeinleinSupport/check_mk#24]
Hi,

habe gerade die beiden Ceph Checks eingerichtet.
Ceph Status klappt wunderbar.
Beeim Ceph Pools bekomme ich beim inventarisieren in Check_MK folgenden Fehler:

Invalid check parameter: The type must be a dictionary, but it is a list! The parameter is: [] The variable name is: checkgroup_parameters:filesystem

<img width="1524" alt="bildschirmfoto 2017-08-25 um 13 05 32" src="https://user-images.githubusercontent.com/10834289/29711642-193c9782-8996-11e7-9e48-a094903fde13.png">

**Comment by mika** [comment]
I can acknowledge that, same problem here.

With ceph v12.2 the `ceph` check also (additionally to `cephpools`) fails with `Unable to find status information.`, because the status output changed:

```
% sudo ceph -s 
  cluster:
    id:     e69d8a96-7008-4599-b3b7-55350b02b042
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum 0,1,2
    mgr: foo1(active), standbys: foo2, foo2
    osd: 18 osds: 18 up, 18 in
 
  data:
    pools:   1 pools, 256 pgs
    objects: 26525 objects, 101421 MB
    usage:   308 GB used, 26483 GB / 26792 GB avail
    pgs:     256 active+clean
```

**Comment by cdwertmann** [comment]
Same issue here with check_mk 1.4.0p10 and ceph jewel. `cephpools` report "UNKNOWN - invalid output from agent or error in check implementation".

**Comment by mika** [comment]
I can confirm that with the fix from @mrgum the cephpools check works fine (thanks!).
The `ceph` check fails against v12.2 though.

**Comment by mika** [comment]
JFTR, we've deployed the change from PR #27 successfully on our infrastructure with ceph v12.2
