### ISSUE TITLE
cephpools: performance graphs s

### ISSUE THREAD

**Issue by sparktown** [HeinleinSupport/check_mk#28]
Die Performance Graphen zeigen bei mir inkorrekte Daten an, obwohl der Service Output stimmt. Im Graph filesystem_size ist die Größe um zwei Einheiten verschoben (MB statt TB), used, free, warn & crit werden gar nicht angezeigt, die anderen Graphen ergeben überhaupt keinen Sinn:

![graphs](https://user-images.githubusercontent.com/34061568/33318829-76d85cdc-d43c-11e7-9436-54cdceeb9dff.png)

Hab sowohl unter 1.4.0p7 als auch unter 1.2.8p26 (beides cee) getestet. Kann jemand das reproduzieren?

**Comment by gurubert** [comment]
I baue das Ceph-Plugin gerade um, so daß die Performance-Daten genauer und auch mehr werden.
