### ISSUE TITLE
check huawei_port crashed

### ISSUE THREAD

**Issue by lgbff** [HeinleinSupport/check_mk#29]
Hi,

the check is crached with this error:

Exception | KeyError (u'0')
-- | --
Traceback | File "/omd/sites/pdm_test/share/check_mk/modules/check_mk_base.py", line 1460, in execute_check     result = sanitize_check_result(check_function(item, params, info), check_uses_snmp(checkname))    File "/omd/sites/pdm_test/local/share/check_mk/checks/huawei_port", line 110, in check_huawei_port     msg += '; port mode: %s' % huawei_port_modes[portinfo[16]]
Local Variables | {'item': u'C01 C01 T00 C00 P00 01',  'msg': u'FC-Port @ CTE0.A.IOM1.P0; WWN: 2008e4c2d1fd27a2; configured rate: auto; speed: 8 Gbit/s',  'params': {'configRate': u'0',             'logicType': u'1',             'mode': u'0',             'speedRate': u'8',             'status': u'1'},  'parsed': {'C01 C01 T00 C00 P00 01': ['FC',                                        u'CTE0.A.IOM1.P0',                                        u'3',                                        u'14',                                        u'0',                                        u'0',                                        u'1114368',                                        u'1',                                        u'1',                                        u'2008e4c2d1fd27a2',                                        u'1114368',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'2008e4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C00 P01 01': ['FC',                                        u'CTE0.A.IOM1.P1',                                        u'3',                                        u'24',                                        u'0',                                        u'0',                                        u'1114369',                                        u'1',                                        u'1',                                        u'2009e4c2d1fd27a2',                                        u'1114369',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'2009e4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C00 P02 01': ['FC',                                        u'CTE0.A.IOM1.P2',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'1114370',                                        u'1',                                        u'1',                                        u'200ae4c2d1fd27a2',                                        u'1114370',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'200ae4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C00 P03 01': ['FC',                                        u'CTE0.A.IOM1.P3',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'1114371',                                        u'1',                                        u'1',                                        u'200be4c2d1fd27a2',                                        u'1114371',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'200be4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C01 P00 01': ['FC',                                        u'CTE0.B.IOM1.P0',                                        u'10',                                        u'72',                                        u'0',                                        u'2',                                        u'17891584',                                        u'1',                                        u'1',                                        u'2018e4c2d1fd27a2',                                        u'17891584',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'2018e4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C01 P01 01': ['FC',                                        u'CTE0.B.IOM1.P1',                                        u'56',                                        u'103',                                        u'0',                                        u'1',                                        u'17891585',                                        u'1',                                        u'1',                                        u'2019e4c2d1fd27a2',                                        u'17891585',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'2019e4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C01 P02 01': ['FC',                                        u'CTE0.B.IOM1.P2',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'17891586',                                        u'1',                                        u'1',                                        u'201ae4c2d1fd27a2',                                        u'17891586',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'201ae4c2d1fd27a2',                                        u'0'],             'C01 C01 T00 C01 P03 01': ['FC',                                        u'CTE0.B.IOM1.P3',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'17891587',                                        u'1',                                        u'1',                                        u'201be4c2d1fd27a2',                                        u'17891587',                                        u'1',                                        u'1',                                        u'0',                                        u'8',                                        u'201be4c2d1fd27a2',                                        u'0'],             'C02 C00 T00 C00 P00 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'131072',                                        u'5',                                        u'1',                                        u'2c:ab:00:7b:dc:08',                                        u'131072',                                        u'1',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C00 P01 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'131073',                                        u'5',                                        u'1',                                        u'2c:ab:00:7b:dc:08',                                        u'131073',                                        u'1',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C00 P02 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'131074',                                        u'5',                                        u'0',                                        u'2c:ab:00:7b:dc:08',                                        u'131074',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C00 P03 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'131075',                                        u'5',                                        u'0',                                        u'2c:ab:00:7b:dc:08',                                        u'131075',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C01 P00 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16908288',                                        u'5',                                        u'1',                                        u'88:cf:98:db:b8:9d',                                        u'16908288',                                        u'1',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C01 P01 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16908289',                                        u'5',                                        u'1',                                        u'88:cf:98:db:b8:9d',                                        u'16908289',                                        u'1',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C01 P02 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16908290',                                        u'5',                                        u'0',                                        u'88:cf:98:db:b8:9d',                                        u'16908290',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C00 T00 C01 P03 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16908291',                                        u'5',                                        u'0',                                        u'88:cf:98:db:b8:9d',                                        u'16908291',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C00 P00 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'139264',                                        u'1',                                        u'5',                                        u'10.133.18.81',                                        u'255.255.255.0',                                        u'0'],             'C02 C32 T00 C00 P02 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'139266',                                        u'0',                                        u'8',                                        u'172.31.128.101',                                        u'255.255.255.0',                                        u'0'],             'C02 C32 T00 C00 P03 00': ['iSCSI',                                        u'CTE0.A.H0',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'139267',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:3c',                                        u'139267',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C00 P04 00': ['iSCSI',                                        u'CTE0.A.H1',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'139268',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:3e',                                        u'139268',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C00 P05 00': ['iSCSI',                                        u'CTE0.A.H2',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'139269',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:3b',                                        u'139269',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C00 P06 00': ['iSCSI',                                        u'CTE0.A.H3',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'139270',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:3d',                                        u'139270',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C01 P00 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16916480',                                        u'1',                                        u'5',                                        u'10.133.18.82',                                        u'255.255.255.0',                                        u'0'],             'C02 C32 T00 C01 P02 00': ['iSCSI',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'16916482',                                        u'0',                                        u'8',                                        u'172.31.128.102',                                        u'255.255.255.0',                                        u'0'],             'C02 C32 T00 C01 P03 00': ['iSCSI',                                        u'CTE0.B.H0',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'16916483',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:2e',                                        u'16916483',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C01 P04 00': ['iSCSI',                                        u'CTE0.B.H1',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'16916484',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:30',                                        u'16916484',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C01 P05 00': ['iSCSI',                                        u'CTE0.B.H2',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'16916485',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:2d',                                        u'16916485',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C32 T00 C01 P06 00': ['iSCSI',                                        u'CTE0.B.H3',                                        u'0',                                        u'0',                                        u'0',                                        u'0',                                        u'16916486',                                        u'5',                                        u'0',                                        u'a8:ca:7b:bc:da:2f',                                        u'16916486',                                        u'0',                                        u'1',                                        u'0.0.0.0',                                        u'0.0.0.0',                                        u'0'],             'C02 C96 T00 C00 P00 09': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'278028288',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'5203db201f41103f'],             'C02 C96 T00 C00 P01 09': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'278028289',                                        u'0',                                        u'4',                                        u'-1',                                        u'-1',                                        u'5203db201f41103f'],             'C02 C97 T00 C01 P00 09': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'294805760',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'5203db201f41113f'],             'C02 C97 T00 C01 P01 09': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'294805761',                                        u'0',                                        u'4',                                        u'-1',                                        u'-1',                                        u'5203db201f41113f'],             'C15 C32 T00 C00 P01 01': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'2039809',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'50022a1060708000'],             'C15 C32 T00 C00 P02 01': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'2039810',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'50022a1060708000'],             'C15 C32 T00 C01 P01 01': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'18817025',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'50022a1060708100'],             'C15 C32 T00 C01 P02 01': ['SAS',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'',                                        u'18817026',                                        u'1',                                        u'4',                                        u'12',                                        u'12',                                        u'50022a1060708100']},  'perfdata': [],  'portinfo': ['FC',               u'CTE0.A.IOM1.P0',               u'3',               u'14',               u'0',               u'0',               u'1114368',               u'1',               u'1',               u'2008e4c2d1fd27a2',               u'1114368',               u'1',               u'1',               u'0',               u'8',               u'2008e4c2d1fd27a2',               u'0'],  'res': 0}

Regards 
Karsten

**Comment by gurubert** [comment]
Hi Karsten,

can you please test if it works with the latest version?

**Comment by lgbff** [comment]
Yes it's work.

thx and br Karsten
