### ISSUE TITLE
Ceph Plugin not shown (inventory)

### ISSUE THREAD

**Issue by n3roGit** [HeinleinSupport/check_mk#33]
Hello,

we're trying to get your ceph plugin to work.
We use the following versions here:

CheckMK: 1.4.0p 26
Ceph: 12.2.5-1xenial

After the MKP has been installed, you can see the ceph data in the agend output. However, the new service is not displayed in WATO.

Agent and server show the following:
####################################################################
root@ceph-02:/usr/lib/check_mk_agent/plugins# ./ceph 
<<<ceph>>>>
  cluster:
    id: 2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum tn-ceph-01,tn-ceph-02,tn-ceph-03
    mgr: tn-ceph-controller(active), standbys: tn-ceph-01
    osd: 12 osds: 12 up, 12 in
 
  data:
    pools: 2 pools, 256 pgs
    objects: 37110 objects, 144 GB
    usage:   445 GB used, 21015 GB / 21460 GB avail
    pgs:     256 active+clean
 
  io:
    client: 0 fps rd, 798 kB/s wr, 0 op/s rd, 18 op/s wr
 
<<<cephpools>>>>
GLOBAL:
    SIZE AVAIL RAW USED %RAW USED 
    21460G 21015G 445G 2.08 
POOLS:
    NAME ID USED %USED MAX AVAIL OBJECTS 
    storage 1 59952M 0.88 6609G 15122 
    myytestpool 3 87948M 1.28 6609G 21988 

####################################################################

If the MKP 5.7 is installed, we get the following errors:
####################################################################
mkp list ceph
Error in plugin file /omd/sites/neusta/local/share/check_mk/checks/cephdf: name 'parse_json' is not defined
Error in plugin file /omd/sites/neusta/local/share/check_mk/checks/cephosd: name 'parse_json' is not defined
Error in plugin file /omd/sites/neusta/local/share/check_mk/checks/cephstatus: name 'parse_json' is not defined
/omd/sites/neusta/local/share/check_mk/checks/ceph
/omd/sites/neusta/local/share/check_mk/checks/cephpools
/omd/sites/neusta/local/share/check_mk/checks/cephdf
/omd/sites/neusta/local/share/check_mk/checks/cephosd
/omd/sites/neusta/local/share/check_mk/checks/cephstatus
/omd/sites/neusta/local/share/check_mk/agents/bakery/ceph
/omd/sites/neusta/local/share/check_mk/agents/plugins/ceph
/omd/sites/neusta/local/share/check_mk/web/plugins/wato/agent_bakery_ceph.py
/omd/sites/neusta/local/share/check_mk/web/plugins/metrics/ceph.py
/omd/sites/neusta/local/share/check_mk/pnp-templates/check_mk-cephdf.php
/omd/sites/neusta/local/share/check_mk/pnp-templates/check_mk-cephosd.php
/omd/sites/neusta/local/share/check_mk/pnp-templates/check_mk-cephpools.php
/omd/sites/neusta/local/share/check_mk/pnp-templates/check_mk-cephstatus.php
####################################################################

But the plugin is loaded:
####################################################################
check_mk -L |grep ceph
ceph tcp (no man page present)
cephpools tcp (no man page present)
####################################################################

With version 4.1 this does not happen.

However, in both cases it does not work as desired.

**Comment by n3roGit** [comment]
I'm sorry. We were too dumb. close

**Comment by thaonguyenvan** [comment]
> I'm sorry. We were too dumb. close

Sorry, how can u fix that?
