### ISSUE TITLE
dell_sc_ctlrfan plugin: TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by agabellini** [HeinleinSupport/check_mk#35]
Hello,

as the title says, this plugin has an error at line 58:

            info_text = "%s, %s RPM, State is %s %s" % (
                line[2],
                line[3],
                ctlrfan_state[0],
            )

It requests 4 arguments but ony three are present. Probably the fourth %s is not needed.

Andrea

**Comment by gurubert** [comment]
Must have been a copy&paste error
