### ISSUE TITLE
ceph: Function size_trend not found after upgrade to check_mk 1.5.0

### ISSUE THREAD

**Issue by elBasti86** [HeinleinSupport/check_mk#39]
After upgrading to check_mk version 1.5.0 all ceph checks crash with the following exception:

MKGeneralException (Function size_trend not found. Please include "size_trend.include" in your check)

I was able to fix it by adding the size_trend.include in those files:
/omd/sites/fc/local/share/check_mk/checks/cephstatus
/omd/sites/fc/local/share/check_mk/checks/cephosd
/omd/sites/fc/local/share/check_mk/checks/cephpools
/omd/sites/fc/local/share/check_mk/checks/cephdf

**Comment by gurubert** [comment]
Thanks for reporting this. I will update my development environment to 1.5 in the next few weeks. After that all these issues should be resolved.

**Comment by gurubert** [comment]
fixed with commit 68833b2fc89ce93a0bd3af9a9e9d302202db656e
