### ISSUE TITLE
kemplb: inventory not working / snmp_scan_function OID not available

### ISSUE THREAD

**Issue by sitweak** [HeinleinSupport/check_mk#4]
Hey, we had a small issue here with the inventory function today. it seems like the snmp_scan_function is checking an OID which is not necessarily available in every configuration.

I described the problem and solution here: http://sitweak.wordpress.com/2014/05/14/problem-solved-monitoring-kemp-loadbalancers-with-check_mk-kemplb_real_servers-kemplb_rsvs-and-kemp_virtual_server/. Feel free to contact me on twitter or leave a comment in my blog.

Thanks for your effort!

Heiko

**Comment by gurubert** [comment]
has been fixed in commit c487e099b395d0f97f0edc09699bed747a90cefd
