### ISSUE TITLE
systemd check not compatible with recent check_mk

### ISSUE THREAD

**Issue by marcvwag** [HeinleinSupport/check_mk#40]
Hi, 

Your systemd plugin does not work anymore. Found 2 issues/changes;
* https://mathias-kettner.de/check_mk-werks.php?werk_id=4236 (Removed g_hostname and g_service_description from Check API)
* NameError: global name 'cmk' is not defined (can be fixed by adding import cmk.paths to check)

Could you please fix/update this plugin?
I am using the latest release; Check_MK version 1.5.0p1 CRE
Thanks!

Marc

**Comment by gurubert** [comment]
Thanks for reporting this. I will update my development environment to 1.5 in the next few weeks. After that all these issues should be resolved.

**Comment by gurubert** [comment]
g_hostname has been replaced by host_name()
g_service_description has been replaced by service_description()

Seee https://mathias-kettner.de/check_mk-werks.php?werk_id=4236&HTML=yes

**Comment by gurubert** [comment]
fixed by commit 5287e0f0c19cbd9d38ab1f4fa3e452e34df6b1c2
