### ISSUE TITLE
Illegal scan function in check_infortrend*

### ISSUE THREAD

**Issue by FlorianHeigl** [HeinleinSupport/check_mk#6]
Hi,

I'll be making some patches but in case you're headscratching:

The infortrend checks have a check function that probs for an OIDs existance.
A check function shouldn't access any external non-cached data if data can be pulled from cache.
So fix is to only look if the infortrend mib subtree is listed in the 1.3.4.1.6.1....2 oid.

Anyway, will be making a pr.

**Comment by gurubert** [comment]
The issue is that the SNMP agent of the Infortrend devices I have access to does not offer the standard SNMP MIBs. It only has the OIDs below .1.3.6.1.4.1.1714.
